import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatSheet from "@/components/chat/chat-sheet";
import { FloatingBIAgent } from "@/components/floating-bi-agent";
import { DashboardProvider } from "@/contexts/dashboard-context";
import { ComponentInsightsPopup } from "@/components/component-insights-popup";
import { MultiSelectIndicator } from "@/components/multi-select-indicator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DashboardProvider>
          {children}
          <ChatSheet />
          <FloatingBIAgent />
          <ComponentInsightsPopup />
          <MultiSelectIndicator />
        </DashboardProvider>
      </body>
    </html>
  );
}
